### ISSUE TITLE
LSig Support

### ISSUE THREAD

**Issue by aorumbayev** [algorand-devrel/beaker#49]
Hello @barnjamin, 

Just curious to hear on whether Smart Signatures are currently supported or beaker mostly aimed for stateful smart contracts? 
Wasn't obvious from the docs whether it's possible hence sending this issue as a question inquiry. 

Thanks for reply in advance!

**Comment by barnjamin** [comment]
Hi @aorumbayev,

Not _really_ yet, beaker deals a lot with the ABI and the ABI requires that routing arguments be passed in the app args array. It does not preclude their use but nothing in beaker really helps with it.

I started a PR here to experiment with different ways to do things with lsigs
https://github.com/algorand-devrel/beaker/pull/33 

The current approach there is for a simple lsig with 1 function, to validate an ETH style signature, in order to offload computation heavy work onto the lsig and save ops for the application.

If you've got ideas I'd love to hear them!

**Comment by barnjamin** [comment]
closing in favor of #55
